"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class constants(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class svg_attrs_whitelist(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        a: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
        altglyph: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
        altglyphdef: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

        def __init__(self,
            *,
            a : typing___Optional[typing___Iterable[typing___Text]] = None,
            altglyph : typing___Optional[typing___Iterable[typing___Text]] = None,
            altglyphdef : typing___Optional[typing___Iterable[typing___Text]] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"a",b"a",u"altglyph",b"altglyph",u"altglyphdef",b"altglyphdef"]) -> None: ...
    type___svg_attrs_whitelist = svg_attrs_whitelist

    class supported_content_languages(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        code: typing___Text = ...
        description: typing___Text = ...
        direction: typing___Text = ...

        def __init__(self,
            *,
            code : typing___Optional[typing___Text] = None,
            description : typing___Optional[typing___Text] = None,
            direction : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"code",b"code",u"description",b"description",u"direction",b"direction"]) -> None: ...
    type___supported_content_languages = supported_content_languages

    CAN_SEND_ANALYTICS_EVENTS: builtin___bool = ...
    CLASSROOM_URL_FRAGMENT_FOR_UNATTACHED_TOPICS: typing___Text = ...
    DEFAULT_CLASSROOM_URL_FRAGMENT: typing___Text = ...
    ALL_CATEGORIES: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
    MAX_COMMIT_MESSAGE_LENGTH: builtin___int = ...

    @property
    def SVG_ATTRS_WHITELIST(self) -> type___constants.svg_attrs_whitelist: ...

    @property
    def SUPPORTED_CONTENT_LANGUAGES(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___constants.supported_content_languages]: ...

    def __init__(self,
        *,
        CAN_SEND_ANALYTICS_EVENTS : typing___Optional[builtin___bool] = None,
        CLASSROOM_URL_FRAGMENT_FOR_UNATTACHED_TOPICS : typing___Optional[typing___Text] = None,
        DEFAULT_CLASSROOM_URL_FRAGMENT : typing___Optional[typing___Text] = None,
        ALL_CATEGORIES : typing___Optional[typing___Iterable[typing___Text]] = None,
        MAX_COMMIT_MESSAGE_LENGTH : typing___Optional[builtin___int] = None,
        SVG_ATTRS_WHITELIST : typing___Optional[type___constants.svg_attrs_whitelist] = None,
        SUPPORTED_CONTENT_LANGUAGES : typing___Optional[typing___Iterable[type___constants.supported_content_languages]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"SVG_ATTRS_WHITELIST",b"SVG_ATTRS_WHITELIST"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"ALL_CATEGORIES",b"ALL_CATEGORIES",u"CAN_SEND_ANALYTICS_EVENTS",b"CAN_SEND_ANALYTICS_EVENTS",u"CLASSROOM_URL_FRAGMENT_FOR_UNATTACHED_TOPICS",b"CLASSROOM_URL_FRAGMENT_FOR_UNATTACHED_TOPICS",u"DEFAULT_CLASSROOM_URL_FRAGMENT",b"DEFAULT_CLASSROOM_URL_FRAGMENT",u"MAX_COMMIT_MESSAGE_LENGTH",b"MAX_COMMIT_MESSAGE_LENGTH",u"SUPPORTED_CONTENT_LANGUAGES",b"SUPPORTED_CONTENT_LANGUAGES",u"SVG_ATTRS_WHITELIST",b"SVG_ATTRS_WHITELIST"]) -> None: ...
type___constants = constants
