# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assets/constants.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='assets/constants.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x61ssets/constants.proto\"\xa4\x01\n\tconstants\x12!\n\x19\x43\x41N_SEND_ANALYTICS_EVENTS\x18\x01 \x01(\x08\x12\x34\n,CLASSROOM_URL_FRAGMENT_FOR_UNATTACHED_TOPICS\x18\x02 \x01(\t\x12&\n\x1e\x44\x45\x46\x41ULT_CLASSROOM_URL_FRAGMENT\x18\x03 \x01(\t\x12\x16\n\x0e\x41LL_CATEGORIES\x18\x04 \x03(\tb\x06proto3')
)




_CONSTANTS = _descriptor.Descriptor(
  name='constants',
  full_name='constants',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CAN_SEND_ANALYTICS_EVENTS', full_name='constants.CAN_SEND_ANALYTICS_EVENTS', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CLASSROOM_URL_FRAGMENT_FOR_UNATTACHED_TOPICS', full_name='constants.CLASSROOM_URL_FRAGMENT_FOR_UNATTACHED_TOPICS', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DEFAULT_CLASSROOM_URL_FRAGMENT', full_name='constants.DEFAULT_CLASSROOM_URL_FRAGMENT', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ALL_CATEGORIES', full_name='constants.ALL_CATEGORIES', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['constants'] = _CONSTANTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

constants = _reflection.GeneratedProtocolMessageType('constants', (_message.Message,), dict(
  DESCRIPTOR = _CONSTANTS,
  __module__ = 'assets.constants_pb2'
  # @@protoc_insertion_point(class_scope:constants)
  ))
_sym_db.RegisterMessage(constants)


# @@protoc_insertion_point(module_scope)
