name: Mypy Type Checks
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  run_tests:
    name: Run Mypy Type Checks
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
          architecture: 'x64'
      - name: Setup python by installing wheel
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: pip2 install wheel==0.35.0
      - name: Install Third Party Dependencies
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: alias python=python2 && python2 -m scripts.install_third_party_libs
      - name: Run Mypy type checks
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: pip3 install mypy && PYTHONIOENCODING=utf-8 python2 -m scripts.run_mypy_checks
