name: Custom ESLint tests
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  run_tests:
    name: Run Mypy type checks.
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Setup python by installing wheel
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: pip install wheel==0.35.0
      - name: Install Third Party Dependencies
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: python -m scripts.install_third_party_libs
      - name: Run Mypy type checks.
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: python3 -m scripts.run_mypy_checks
